---
  - name: install nop commerce
    become: yes
    hosts: all
    vars:
      - mysql_username: mysql
      - mysql_home_directory: /usr/local/mysql
    tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install openjdk-8-jdk
      apt:
        name: openjdk-8-jdk
        state: present
    - name: Creating MYSQL group
      group:
        name: "{{ mysql_username }}"
        state: present
    - name: Add mysql user with mysql group
      ansible.builtin.user:
        name: "{{ mysql_username }}"
        group: admin
    - name: Download mysql file
      get_url:
        url: https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.46-linux-glibc2.12-x86_64.tar.gz
        dest: .
        mode: '0777'
    - name: Create mysql home directory
      ansible.builtin.file:
        path: "{{ mysql_home_directory }}"
        state: directory
        mode: '0777'
    - name: Unarchive mysql
      ansible.builtin.unarchive:
        src: /home/suresh/mysql-5.6.46-linux-glibc2.12-x86_64.tar.gz
        dest: "{{ mysql_home_directory }}"
        remote_src: yes
    - name: Change ownership mysql home directory
      ansible.builtin.file:
        path: "{{ mysql_home_directory }}"
        state: directory
        recurse: yes
        group: mysql
        owner: mysql
        mode: '0777'
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - libaio1
        - libncurses5
        - libnuma-dev
    - name: Run mysql command
      command:
        cmd: /usr/local/mysql/mysql-5.6.46-linux-glibc2.12-x86_64/scripts/mysql_install_db --user=mysql
    