 ---
  - name: install nop commerce
    become: yes
    hosts: all
    vars:
      - mysql_username: mysql
      - mysql_home_directory: /usr/local/mysql
    tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install openjdk-8-jdk
      apt:
        name: openjdk-8-jdk
        state: present
    - name: Creating MYSQL group
      group:
        name: "{{ mysql_username }}"
        state: present
    - name: Add mysql user with mysql group
      ansible.builtin.user:
        name: "{{ mysql_username }}"
        group: admin
    - name: Download mysql file
      get_url:
        url: https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.46-linux-glibc2.12-x86_64.tar.gz
        dest: .
        mode: '0777'
    - name: Create mysql home directory
      ansible.builtin.file:
        path: "{{ mysql_home_directory }}"
        state: directory
        mode: '0777'
    - name: Unarchive mysql
      ansible.builtin.unarchive:
        src: /home/suresh/mysql-5.6.46-linux-glibc2.12-x86_64.tar.gz
        dest: "{{ mysql_home_directory }}"
        remote_src: yes
    - name: Change ownership mysql home directory
      ansible.builtin.file:
        path: "{{ mysql_home_directory }}"
        state: directory
        recurse: yes
        group: mysql
        owner: mysql
        mode: '0777'
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - libaio1
        - libncurses5
        - libnuma-dev
    - name: Change ownership mysql home directory
      ansible.builtin.file:
        path: "{{ mysql_home_directory }}"
        state: directory
        recurse: yes
        owner: root
        mode: '0755'
    - name: Change ownership mysql home directory
      ansible.builtin.file:
        path: "{{ mysql_home_directory }}/data"
        state: directory
        recurse: yes
        owner: root
        mode: '0755'    
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: "{{ mysql_home_directory }}/mysql-5.6.46-linux-glibc2.12-x86_64/support-files/my-default.cnf"
        dest: /etc/my.cnf
        remote_src: yes
        mode: '0777'
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: "{{ mysql_home_directory }}/mysql-5.6.46-linux-glibc2.12-x86_64/support-files/mysql.server"
        dest: /etc/init.d/mysql.server
        remote_src: yes
        mode: '0777'
    - name: Run command if /path/to/database does not exist (with 'cmd' parameter)
      ansible.builtin.command:
        chdir: "{{ mysql_home_directory }}/mysql-5.6.46-linux-glibc2.12-x86_64"
        cmd: bin/mysqld_safe --user=mysql & bin/mysqladmin -u root password newpassword
    - name: Create a symbolic link
      ansible.builtin.file:
        src: /usr/local/mysql/mysql-5.6.46-linux-glibc2.12-x86_64/bin/mysql
        dest: /usr/local/bin/mysql
        state: link
    - name: Make sure apache2 is started
      sysvinit:
          name: mysql.server
          state: started
          enabled: yes
    - name: Ensure group "somegroup" exists
      group:
       name: somegroup
       state: presents