---
  - name: install nop commerce
    become: yes
    hosts: all
    vars:
      - mysql_username: mysql
    tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install openjdk-8-jdk
      apt:
        name: openjdk-8-jdk
        state: present
    - name: Creating MYSQL group
      group:
        name: "{{ mysql_username }}"
        state: present
    - name: Add mysql user with mysql group
      ansible.builtin.user:
        name: "{{ mysql_username }}"
        group: admin
    - name: Download mysql file
      get_url:
        url: https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.46-linux-glibc2.12-x86_64.tar.gz
        dest: .
        mode: '0755'